### ISSUE TITLE
HackTheGraph (Hackathon) Todo List

### ISSUE THREAD

**Issue by petervann** [petervann/hackTheGraph#4]
## TODO LIST

*Tasks left to complete:*

* [ ] Add the theme name as a label on the lower left corner of the grid
* [ ] Add a way to 'clear' the grid (make all the pixels #eee)
* [ ] Make a way to reference a day/pixel by x/y coordinates (aka week/day)
* [ ] Create a theme customizer
* [ ] Fully realize the Kylo Ren slide (Lightsaber drawn dynamically, Legend labels: Light/Dark)
* [ ] Fully realize the Dancing Colors slide (Pixels changes colors randomly)
* [ ] Fully realize the Troll Face slide (teeth rendered dynamically)
* [ ] Create a Pacman Slide (animated Pacman characters)
* [ ] Create a Tetris Slide (fully animated)

(Add more tasks as we think of them...)
